# Generated by Django 4.2 on 2025-02-23 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('counrty', models.CharField(max_length=100)),
            ],
        ),
    ]
